import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dist=path.join(root,'dist');
const required=['studio.html','index.html','mobile-entry.js','mobile-shell.js','mobile.css','vocal-bridge.js','bungee-processor-bundled.js','workstation/app.js','workstation/producer-ui.js','workstation/precision-ui.js','workstation/mixer-ui.js','lab/index.html','lab/mobile-classic.js','lab/studio-runtime.js','lab/mp3-codec.js'];
for(const rel of required){const p=path.join(dist,rel);const st=await fs.stat(p).catch(()=>null);if(!st?.isFile()||st.size<20)throw Error('Missing native web payload: '+rel);}
const studio=await fs.readFile(path.join(dist,'studio.html'),'utf8');
if(!studio.includes("mobile-entry.js")||!studio.includes('mobile.css'))throw Error('Studio is not using mobile entry/CSS.');
if(studio.includes("src='./entry.js'"))throw Error('Web collaboration bootstrap leaked into native studio.');
const shell=await fs.readFile(path.join(dist,'mobile-shell.js'),'utf8');
for(const marker of ['saveFile','signIn','hostCheck','checkUpdates','nation.infectedvoices.space','purchaseSubscription','infectedvoices.studio.monthly','/api/health','0.6.6-mobile.2','Authorization'])if(!shell.includes(marker))throw Error('Mobile bridge missing '+marker);
const entry=await fs.readFile(path.join(dist,'mobile-entry.js'),'utf8');
if(entry.includes('Core6Collaboration'))throw Error('Unreleased Core 6 collaboration bootstrap leaked into the Core 5 mobile release.');
const chrome=await fs.readFile(path.join(dist,'mobile-chrome.js'),'utf8');
for(const marker of ['mobileHostSettings','mobileUpdates','mobileStore','mobileNationAccount','device-v1','hostCheck','checkUpdates','installUpdate','core3Mixer','core5Producer','Open store listing','Check RedXAIHost Studio','Search features','GRIM rack','Precision Tune','Vocal Lab','Apple signup','Studio Plus','Stripe is not used','ivOpenNativeStore'])if(!chrome.includes(marker))throw Error('Mobile chrome missing '+marker);
const home=await fs.readFile(path.join(dist,'index.html'),'utf8');
if(!home.includes('content="0.7.0"')||!home.includes('vocal-bridge.js'))throw Error('Cap home is not Vocal Lab 0.7.0.');
if(home.includes('Two voices'))throw Error('Core 6 collaboration pilot is still the Cap launch page.');
const css=await fs.readFile(path.join(dist,'mobile.css'),'utf8');
for(const marker of ['#09090B','#6E79D6','#27272A','--surface','--touch','--accent-muted','safe-area-inset','mobile-tabbar','--iv-accent','infected-auth-choices','apple-auth'])if(!css.includes(marker))throw Error('Mobile stylesheet missing '+marker);
const font=await fs.stat(path.join(dist,'fonts','InterVariable.woff2')).catch(()=>null);
if(!font?.isFile()||font.size<1000)throw Error('Inter font missing from mobile web payload.');
const create=await fs.readFile(path.join(dist,'mobile-create.js'),'utf8');
const entitlements=await fs.readFile(path.join(dist,'entitlements.js'),'utf8');
const flow=create+'\n'+entitlements;
for(const marker of ['ivModeCreate','ivModeStudio','Unlock with Pro','Get Pro — $40','Maybe later','Hit REC and spit a take. Headphones help.','Tour complete — open Studio for advanced.','Open advanced settings','Export stems','AI Beat-Lock','Vocal isolation'])if(!flow.includes(marker))throw Error('Create flow missing '+marker);
const {selfCheck}=await import('../mobile-src/entitlements.js');
selfCheck();
const download=await fs.readFile(path.join(root,'download','index.html'),'utf8');
for(const marker of ['App Store','Google Play','Windows installer from Releases when available','View Windows Releases','https://github.com/grimvirusoffical-source/InfectedVoices-Windows/releases/latest','/voices','No Mac .app','does not offer an ipa','does not offer an aab','not the Windows app'])if(!download.includes(marker))throw Error('Download page missing '+marker);
if(/signed/i.test(download)||/sha-?256/i.test(download))throw Error('Download page must not claim a signed Windows build or publish a checksum before an Authenticode Release exists.');
const server=await fs.readFile(path.join(root,'scripts','redx-browser-server.mjs'),'utf8');
if(!server.includes('pathname==="/get"')||!server.includes('pathname==="/download"'))throw Error('/get is not the same page as /download.');
if(!server.includes('provider_not_configured')||!server.includes('503'))throw Error('Cloud AI routes must stay real 503s.');
console.log(JSON.stringify({ok:true,core:'5',files:required.length,studioBytes:(await fs.stat(path.join(dist,'studio.html'))).size,shellBytes:(await fs.stat(path.join(dist,'mobile-shell.js'))).size}));
